services:
  - type: web
    name: ransomware-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level debug
    envVars:
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: ""
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: DEST_EMAIL
        value: ""
      - key: STATS_DB
        value: "/data/stats.db"
      - key: DATABASE_URL
        value: ""  # e.g. postgres://user:pass@host:5432/dbname
    healthCheckPath: /api
    autoDeploy: true
